name: Build and Push Documentation

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  Docs:
    name: Build and push documentation
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10"
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
      - name: configure and install conda and requirements
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          conda install --quiet --file=requirements.txt
          conda install lsst-documenteer-pipelines
      - name: install rubin_sim
        shell: bash -l {0}
        run: |
          echo `pwd`
          ls ${{ github.workspace }}
          python -m pip install .
      - name: download rubin_sim_data components needed to set up metrics for metricList
        shell: bash -l {0}
        run: |
          export RUBIN_SIM_DATA_DIR=${{ github.workspace }}
          rs_download_data -d 'maf,throughputs'
      - name: conda list
        shell: bash -l {0}
        run: conda list
      - name: build documentation
        shell: bash -l {0}
        run: |
          export RUBIN_SIM_DATA_DIR=${{ github.workspace }}
          cd doc
          python metricList.py
          make html
      - name: Install LTD Conveyor
        shell: bash -l {0}
        run: |
          python -m pip install ltd-conveyor        
      - name: upload documentation
        shell: bash -l {0}
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          ltd upload --gh --dir doc/_build/html --product rubin-sim
